image: python:latest

services:
  - postgres:latest

variables:
  DJANGO_SETTINGS_INI: ci.ini
  POSTGRES_DB: test_postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

before_script:
  - pip install tox

lint:
  script:
  - tox -e lint

test:
  script:
  - tox -e test,coverage
