image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

before_script:
  - pip install tox

lint:
  script:
  - tox -e lint

test:
  script:
  - tox -e ci,coverage
