image: python:latest

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - test

test:
  stage: test
  script:
  - pip install tox
  - tox -e lint, test

coverage:
  stage: test
  script:
  - pip install tox
  - tox -e coverage
  allow_failure: true