# Generated by Django 2.2.1 on 2019-06-13 13:56

import _socket
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('created', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', django_audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('sbsys_id', models.CharField(max_length=128, unique=True, verbose_name='SBSYS-ID')),
                ('cpr_number', models.CharField(max_length=12, verbose_name='cpr-nummer')),
                ('name', models.CharField(max_length=128, verbose_name='Navn')),
                ('target_group', models.CharField(choices=[('FAMILY_DEPT', 'familieafdelingen'), ('DISABILITY_DEPT', 'handicapafdelingen')], max_length=128, verbose_name='målgruppe')),
                ('effort_step', models.CharField(choices=[('STEP_ONE', 'Trin 1: Tidlig indsats i almenområdet'), ('STEP_TWO', 'Trin 2: Forebyggelse'), ('STEP_THREE', 'Trin 3: Hjemmebaserede indsatser'), ('STEP_FOUR', 'Trin 4: Anbringelse i slægt eller netværk'), ('STEP_FIVE', 'Trin 5: Anbringelse i forskellige typer af plejefamilier'), ('STEP_SIX', 'Trin 6: Anbringelse i institutionstilbud')], max_length=128, verbose_name='indsatstrappe')),
                ('scaling_step', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='skaleringstrappe')),
                ('refugee_integration', models.BooleanField(default=False, verbose_name='integrationsindsatsen')),
                ('cross_department_measure', models.BooleanField(default=False, verbose_name='tværgående ungeindsats')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='navn')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('INTERNAL', 'Intern'), ('PERSON', 'Person'), ('COMPANY', 'Firma')], max_length=128, verbose_name='betalingsmodtager')),
                ('recipient_id', models.CharField(max_length=128, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=128, verbose_name='Navn')),
                ('payment_method', models.CharField(choices=[('CASH', 'Udbetaling'), ('SD', 'SD-LØN'), ('INVOICE', 'Faktura'), ('INTERNAL', 'Intern afregning')], max_length=128, verbose_name='betalingsmåde')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='navn')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=128, verbose_name='paragraf')),
                ('kle_number', models.CharField(max_length=128, verbose_name='KLE-nummer')),
                ('text', models.TextField(verbose_name='forklarende tekst')),
                ('target_group', models.CharField(choices=[('FAMILY_DEPT', 'familieafdelingen'), ('DISABILITY_DEPT', 'handicapafdelingen')], max_length=128, verbose_name='målgruppe')),
                ('allowed_for_steps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('STEP_ONE', 'Trin 1: Tidlig indsats i almenområdet'), ('STEP_TWO', 'Trin 2: Forebyggelse'), ('STEP_THREE', 'Trin 3: Hjemmebaserede indsatser'), ('STEP_FOUR', 'Trin 4: Anbringelse i slægt eller netværk'), ('STEP_FIVE', 'Trin 5: Anbringelse i forskellige typer af plejefamilier'), ('STEP_SIX', 'Trin 6: Anbringelse i institutionstilbud')], max_length=128), size=6)),
                ('law_text_name', models.CharField(max_length=128, verbose_name='lov tekst navn')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=128, verbose_name='relation')),
                ('cpr_number', models.CharField(blank=True, max_length=12, verbose_name='cpr-nummer')),
                ('name', models.CharField(max_length=128, verbose_name='navn')),
                ('related_case', models.CharField(blank=True, max_length=128, verbose_name='SBSYS-sag')),
                ('main_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_persons', to='core.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='betalingsdato')),
                ('recipient_type', models.CharField(choices=[('INTERNAL', 'Intern'), ('PERSON', 'Person'), ('COMPANY', 'Firma')], max_length=128, verbose_name='betalingsmodtager')),
                ('recipient_id', models.CharField(max_length=128, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=128, verbose_name='Navn')),
                ('payment_method', models.CharField(choices=[('CASH', 'Udbetaling'), ('SD', 'SD-LØN'), ('INVOICE', 'Faktura'), ('INTERNAL', 'Intern afregning')], max_length=128, verbose_name='betalingsmåde')),
                ('payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.PaymentSchedule')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalCase',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('created', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', django_audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('effort_step', models.CharField(choices=[('STEP_ONE', 'Trin 1: Tidlig indsats i almenområdet'), ('STEP_TWO', 'Trin 2: Forebyggelse'), ('STEP_THREE', 'Trin 3: Hjemmebaserede indsatser'), ('STEP_FOUR', 'Trin 4: Anbringelse i slægt eller netværk'), ('STEP_FIVE', 'Trin 5: Anbringelse i forskellige typer af plejefamilier'), ('STEP_SIX', 'Trin 6: Anbringelse i institutionstilbud')], max_length=128, verbose_name='indsatstrappe')),
                ('scaling_step', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='skaleringstrappe')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case_worker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='sagsbehandler')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical case',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='case',
            name='acting_municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts_on', to='core.Municipality', verbose_name='handlekommune'),
        ),
        migrations.AddField(
            model_name='case',
            name='case_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name='sagsbehandler'),
        ),
        migrations.AddField(
            model_name='case',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core.SchoolDistrict', verbose_name='skoledistrikt'),
        ),
        migrations.AddField(
            model_name='case',
            name='paying_municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pays_for', to='core.Municipality', verbose_name='betalingskommune'),
        ),
        migrations.AddField(
            model_name='case',
            name='residence_municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_clients', to='core.Municipality', verbose_name='bopælskommune'),
        ),
        migrations.CreateModel(
            name='Appropriation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('created', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', django_audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('sbsys_id', models.CharField(max_length=128, unique=True, verbose_name='SBSYS-ID')),
                ('section', models.CharField(max_length=128, verbose_name='paragraf')),
                ('status', models.CharField(choices=[('DRAFT', 'kladde'), ('BUDGETED', 'disponeret'), ('GRANTED', 'bevilget'), ('DISCONTINUED', 'udgået')], max_length=16, verbose_name='status')),
                ('approval_level', models.CharField(blank=True, choices=[('CASE_WORKER', 'egenkompetence'), ('TEAM_MEETING', 'teammøde'), ('SECTION_HEAD', 'fagspecialist'), ('TEAM_LEADER', 'teamleder'), ('SECTION_HEAD', 'afsnitsleder'), ('YOUTH_CRIME_BOARD', 'ungdomskriminalitetsnævnet')], max_length=16, verbose_name='bevilling foretaget på niveau')),
                ('approval_note', models.TextField(blank=True, verbose_name='evt. bemærkning')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appropriations', to='core.Case')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Navn')),
                ('activity_id', models.CharField(max_length=128, verbose_name='Aktivitets ID')),
                ('max_tolerance_in_percent', models.PositiveSmallIntegerField(verbose_name='Max tolerance i procent')),
                ('max_tolerance_in_dkk', models.PositiveIntegerField(verbose_name='Max tolerance i DKK')),
                ('main_activity_for', models.ManyToManyField(related_name='main_activities', to='core.Sections')),
                ('supplementary_activity_for', models.ManyToManyField(related_name='supplementary_activities', to='core.Sections')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('created', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', django_audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('EXPECTED', 'forventet'), ('GRANTED', 'bevilget')], max_length=128, verbose_name='status')),
                ('start_date', models.DateField(verbose_name='startdato')),
                ('end_date', models.DateField(verbose_name='slutdato')),
                ('activity_type', models.CharField(choices=[('MAIN_ACTIVITY', 'hovedaktivitet'), ('SUPPL_ACTIVITY', 'følgeaktivitet'), ('EXPECTED_CHANGE', 'forventning')], max_length=128, verbose_name='type')),
                ('appropriation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.Appropriation')),
                ('main_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_activities', to='core.Activity', verbose_name='hovedaktivitet')),
                ('modifies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to='core.Activity')),
                ('payment_plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PaymentSchedule', verbose_name='betalingsplan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ActivityCatalog')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=128)),
                ('activity_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ActivityCatalog')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sections')),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('activity_catalog', 'section'), name='unique_account_number'),
        ),
    ]
