# Generated by Django 2.2.1 on 2019-08-27 07:29

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [("core", "0002_delete_end_before_start_activities")]

    operations = [
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    start_date__lte=django.db.models.expressions.F("end_date")
                ),
                name="end_date_after_start_date",
            ),
        )
    ]
