# Generated by Django 2.2.1 on 2019-08-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190827_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assessment_comment',
            field=models.TextField(blank=True, verbose_name='supplerende oplysninger til vurdering'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='assessment_comment',
            field=models.TextField(blank=True, verbose_name='supplerende oplysninger til vurdering'),
        ),
    ]
