# Generated by Django 2.2.1 on 2019-10-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191016_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='fictive',
            field=models.BooleanField(default=False, verbose_name='fiktiv'),
        ),
    ]
