# Generated by Django 2.2.1 on 2019-10-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191016_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
    ]
