# Generated by Django 2.2.1 on 2019-10-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191016_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, choices=[('readonly', 'Kun læse'), ('edit', 'Læse og skrive'), ('grant', 'Bevilge'), ('admin', 'Admin')], max_length=128, verbose_name='brugerprofil'),
        ),
    ]
