# Generated by Django 2.2.1 on 2019-09-05 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190830_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appropriation',
            name='appropriation_date',
        ),
        migrations.RemoveField(
            model_name='appropriation',
            name='approval_level',
        ),
        migrations.RemoveField(
            model_name='appropriation',
            name='approval_note',
        ),
        migrations.RemoveField(
            model_name='appropriation',
            name='approval_user',
        ),
        migrations.RemoveField(
            model_name='appropriation',
            name='status',
        ),
        migrations.AddField(
            model_name='activity',
            name='appropriation_date',
            field=models.DateField(blank=True, null=True, verbose_name='bevillingsdato'),
        ),
        migrations.AddField(
            model_name='activity',
            name='approval_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to='core.ApprovalLevel', verbose_name='bevillingsniveau'),
        ),
        migrations.AddField(
            model_name='activity',
            name='approval_note',
            field=models.TextField(blank=True, verbose_name='evt. bemærkning'),
        ),
        migrations.AddField(
            model_name='activity',
            name='approval_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_activities', to=settings.AUTH_USER_MODEL, verbose_name='bevilget af bruger'),
        ),
    ]
