# Generated by Django 2.2.1 on 2019-09-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190830_1345'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='SectionInfo',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                options={
                    'db_table': 'core_activitydetails_main_activity_for',
                    },
                ),
            migrations.RemoveField(
                model_name='section',
                name='kle_number',
                ),
            migrations.RemoveField(
                model_name='section',
                name='sbsys_template_id',
                ),
            migrations.AlterField(
                model_name='activitydetails',
                name='main_activity_for',
                field=models.ManyToManyField(blank=True, related_name='main_activities', through='core.SectionInfo', to='core.Section', verbose_name='hovedaktivitet for paragraffer'),
                ),
            migrations.AddField(
                model_name='sectioninfo',
                name='activity_details',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ActivityDetails'),
                ),
            migrations.AddField(
                model_name='sectioninfo',
                name='section',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Section'),
                ),
            ])
        ]
