# Generated by Django 2.2.1 on 2019-09-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190906_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninfo',
            name='kle_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='KLE-nummer'),
        ),
        migrations.AddField(
            model_name='sectioninfo',
            name='sbsys_template_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='SBSYS skabelon-id'),
        ),
    ]
