# Generated by Django 2.2.1 on 2019-09-05 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190904_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='approval_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_activities', to='core.ApprovalLevel', verbose_name='bevillingsniveau'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='approval_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_activities', to=settings.AUTH_USER_MODEL, verbose_name='bevilget af bruger'),
        ),
    ]
