# Generated by Django 2.2.1 on 2019-09-13 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190905_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_day_of_month',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='betales d.'),
        ),
    ]
