# Generated by Django 2.2.1 on 2019-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_remove_payment_id")]

    operations = [
        migrations.AddField(
            model_name="paymentschedule",
            name="payment_id",
            field=models.PositiveIntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="betalings-ID",
            ),
        )
    ]
