# Generated by Django 2.2.1 on 2019-09-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paymentschedule_payment_day_of_month'),
    ]

    # NOTE: It's currently not possible to add a through class (with
    # extra field) to an existing ManyToManyField. That is due to what
    # is arguably a bug in Django. See the relevant ticket:
    # https://code.djangoproject.com/ticket/23034
    # The workaround below, using ``SeparateDatabaseAndState`` and
    # reusing the name of the intermediate DB table for the through
    # field, is inspired by comment #9 in the above ticket.
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='SectionInfo',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ],
                options={
                    'db_table': 'core_activitydetails_main_activity_for',
                    },
                ),
            migrations.AlterField(
                model_name='activitydetails',
                name='main_activity_for',
                field=models.ManyToManyField(blank=True, related_name='main_activities', through='core.SectionInfo', to='core.Section', verbose_name='hovedaktivitet for paragraffer'),
                ),
            migrations.AddField(
                model_name='sectioninfo',
                name='activity_details',
                field=models.ForeignKey(db_column="activitydetails_id", on_delete=django.db.models.deletion.CASCADE, to='core.ActivityDetails'),
                ),
            migrations.AddField(
                model_name='sectioninfo',
                name='section',
                field=models.ForeignKey(db_column="section_id", on_delete=django.db.models.deletion.CASCADE, to='core.Section'),
                ),
            ])
        ]
