# Generated by Django 2.2.1 on 2019-09-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_import_sbsys_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='kle_number',
        ),
        migrations.RemoveField(
            model_name='section',
            name='sbsys_template_id',
        ),
    ]
