# Generated by Django 2.2.1 on 2019-11-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_payment_saved_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioninfo',
            name='activity_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ActivityDetails', verbose_name='aktivitetsdetalje'),
        ),
        migrations.AlterField(
            model_name='sectioninfo',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Section', verbose_name='paragraf'),
        ),
    ]
