# Generated by Django 2.2.1 on 2019-11-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191111_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='EffortStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='navn')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Nummer')),
            ],
            options={
                'verbose_name': 'indsatstrappetrin',
                'verbose_name_plural': 'indsatstrappe',
            },
        ),
        migrations.AddField(
            model_name='case',
            name='effort_step_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.EffortStep', verbose_name='indsatstrappe'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='effort_step_new',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.EffortStep', verbose_name='indsatstrappe'),
        ),
    ]
