# Generated by Django 2.2.1 on 2019-09-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20190917_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='core.Team', verbose_name='team'),
        ),
    ]
