# Generated by Django 2.2.1 on 2019-11-11 14:18

from django.db import migrations

from django.utils.translation import gettext_lazy as _


def create_effort_steps(apps, schema_editor):
    """Create steps corresponding to the old choice list."""
    EffortStep = apps.get_model("core", "EffortStep")
    effort_steps_values = (
        (1, _("Trin 1: Tidlig indsats i almenområdet")),
        (2, _("Trin 2: Forebyggelse")),
        (3, _("Trin 3: Hjemmebaserede indsatser")),
        (4, _("Trin 4: Anbringelse i slægt eller netværk")),
        (5, _("Trin 5: Anbringelse i forskellige typer af plejefamilier")),
        (6, _("Trin 6: Anbringelse i institutionstilbud")),
    )
    for number, name in effort_steps_values:
        EffortStep.objects.create(name=name, number=number)


def move_effort_steps(apps, schema_editor):
    """Move existing steps to the foreign key field."""
    EffortStep = apps.get_model("core", "EffortStep")
    Case = apps.get_model("core", "Case")
    HistoricalCase = apps.get_model("core", "HistoricalCase")

    for case in Case.objects.all():
        case.effort_step_new = EffortStep.objects.get(number=case.effort_step)
        case.save()

    for historical_case in HistoricalCase.objects.all():
        historical_case.effort_step_new = EffortStep.objects.get(number=case.effort_step)
        historical_case.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191111_1517'),
    ]

    operations = [
        migrations.RunPython(create_effort_steps, move_effort_steps)
    ]
