# Generated by Django 2.2.1 on 2019-11-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transfer_effort_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='effort_step',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='effort_step',
        ),
    ]
