# Generated by Django 2.2.1 on 2019-11-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191111_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='effort_step_new',
            new_name='effort_step',
        ),
        migrations.RenameField(
            model_name='historicalcase',
            old_name='effort_step_new',
            new_name='effort_step',
        ),
    ]
