# Generated by Django 2.2.1 on 2019-11-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191111_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='allowed_for_steps_new',
            field=models.ManyToManyField(blank=True, related_name='sections', to='core.EffortStep', verbose_name='tilladt for trin i indsatstrappen'),
        ),
    ]
