# Generated by Django 2.2.1 on 2019-11-12 08:59

from django.db import migrations


def move_effort_steps(apps, schema_editor):
    """Move steps from the old ArrayField to the new ManyToManyField."""
    EffortStep = apps.get_model("core", "EffortStep")
    Section = apps.get_model("core", "Section")

    for section in Section.objects.all():
        for step in section.allowed_for_steps:
            section.allowed_for_steps_new.add(
                EffortStep.objects.get(number=step)
            )


class Migration(migrations.Migration):

    dependencies = [("core", "0017_section_allowed_for_steps_new")]

    operations = [migrations.RunPython(move_effort_steps)]
