# Generated by Django 2.2.1 on 2019-11-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_section_allowed_for_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='allowed_for_steps_new',
            new_name='allowed_for_steps',
        ),
    ]
