# Generated by Django 2.2.1 on 2019-11-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0020_auto_20191112_1048")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="activity_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="aktivitetsnummer",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="main_account_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                verbose_name="hovedkontonummer",
            ),
        ),
    ]
