# Generated by Django 2.2.1 on 2019-11-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20191118_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effortstep',
            options={'ordering': ['number'], 'verbose_name': 'indsatstrappetrin', 'verbose_name_plural': 'indsatstrappe'},
        ),
    ]
