# Generated by Django 2.2.9 on 2020-02-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_duplicate_payments'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('payment_schedule', 'date'), name='unique_payment_date'),
        ),
    ]
