# Generated by Django 2.2.9 on 2020-03-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200221_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='approval_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_activities', to='core.ApprovalLevel', verbose_name='bevillingsniveau'),
        ),
    ]
