# Generated by Django 2.2.9 on 2020-02-21 12:23

from django.db import migrations


def remove_paymentschedules_without_an_activity(apps, schema_editor):
    PaymentSchedule = apps.get_model("core", "PaymentSchedule")

    payment_schedules = PaymentSchedule.objects.filter(activity__isnull=True)

    for payment_schedule in payment_schedules:
        payment_schedule.delete()


class Migration(migrations.Migration):

    dependencies = [("core", "0027_auto_20200221_1323")]

    operations = [
        migrations.RunPython(remove_paymentschedules_without_an_activity)
    ]
