# Generated by Django 2.2.9 on 2020-03-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_delete_paymentschedules_without_an_activity")
    ]

    operations = [
        migrations.AddField(
            model_name="paymentschedule",
            name="new_activity",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Activity",
                verbose_name="aktivitet",
                related_name="payment_schedule",
            ),
        )
    ]
