# Generated by Django 2.2.1 on 2019-11-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0030_paymentschedule_migrate_activities")]

    operations = [
        migrations.RemoveField(model_name="activity", name="payment_plan"),
        migrations.RenameField(
            model_name="paymentschedule",
            old_name="new_activity",
            new_name="activity",
        ),
    ]
