# Generated by Django 2.2.9 on 2020-04-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_migrate_target_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='target_group',
        ),
    ]
