# Generated by Django 2.2.9 on 2020-04-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_case_target_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='target_group_model',
            new_name='target_group',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='target_group_model',
        ),
    ]
