# Generated by Django 2.2.9 on 2020-04-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_migrate_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='allowed_for_disability_target_group',
        ),
        migrations.RemoveField(
            model_name='section',
            name='allowed_for_family_target_group',
        ),
    ]
