# Generated by Django 2.2.9 on 2020-04-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200427_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydetails',
            name='description',
            field=models.TextField(blank=True, verbose_name='beskrivelse'),
        ),
    ]
