# Generated by Django 2.2.9 on 2020-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_activitydetails_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activitydetails',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='approvallevel',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='effortstep',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schooldistrict',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='targetgroup',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
