# Generated by Django 2.2.9 on 2020-04-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_migrate_efforts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='cross_department_measure',
        ),
        migrations.RemoveField(
            model_name='case',
            name='refugee_integration',
        ),
    ]
