# Generated by Django 2.2.9 on 2020-05-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200506_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('variablerate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.VariableRate')),
                ('name', models.CharField(max_length=128, verbose_name='Navn')),
                ('description', models.TextField(blank=True, verbose_name='beskrivelse')),
            ],
            options={
                'verbose_name': 'takst',
            },
            bases=('core.variablerate',),
        ),
        migrations.CreateModel(
            name='RatePerDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='takst')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='startdato')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='slutdato')),
                ('main_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_per_date', to='core.VariableRate')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('variablerate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.VariableRate')),
                ('payment_schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='core.PaymentSchedule', verbose_name='betalingsplan')),
            ],
            options={
                'verbose_name': 'pris',
            },
            bases=('core.variablerate',),
        ),
    ]
