# Generated by Django 2.2.9 on 2020-05-07 12:17

import _socket
from django.db import migrations, models
import django.utils.timezone
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200506_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedperson',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='device_created',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='device_modified',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='from_serviceplatformen',
            field=models.BooleanField(blank=True, default=True, verbose_name='fra Serviceplatformen'),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='hostname_created',
            field=models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='hostname_modified',
            field=models.CharField(blank=True, help_text='System field. (modified on every save)', max_length=50),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='revision',
            field=models.CharField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision'),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='user_created',
            field=models.CharField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created'),
        ),
        migrations.AddField(
            model_name='relatedperson',
            name='user_modified',
            field=models.CharField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified'),
        ),
    ]
