# Generated by Django 2.2.9 on 2020-05-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20200507_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='effort',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
    ]
