# Generated by Django 2.2.9 on 2020-05-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_price_rate_rateperdate_variablerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninfo',
            name='main_activity_main_account_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='hovedkontonummer for hovedaktivitet'),
        ),
        migrations.AddField(
            model_name='sectioninfo',
            name='supplementary_activity_main_account_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='hovedkontonummer for følgeudgift'),
        ),
    ]
