# Generated by Django 2.2.9 on 2020-05-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_migrate_accounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitydetails',
            options={'ordering': ('name',), 'verbose_name': 'aktivitetsdetalje', 'verbose_name_plural': 'aktivitetsdetaljer'},
        ),
        migrations.AlterModelOptions(
            name='approvallevel',
            options={'ordering': ('name',), 'verbose_name': 'bevillingsniveau', 'verbose_name_plural': 'bevillingsniveauer'},
        ),
        migrations.AlterModelOptions(
            name='effort',
            options={'ordering': ('name',), 'verbose_name': 'indsats', 'verbose_name_plural': 'indsatser'},
        ),
        migrations.AlterModelOptions(
            name='effortstep',
            options={'ordering': ('number',), 'verbose_name': 'indsatstrappetrin', 'verbose_name_plural': 'indsatstrappe'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ('name',), 'verbose_name': 'kommune', 'verbose_name_plural': 'kommuner'},
        ),
        migrations.AlterModelOptions(
            name='schooldistrict',
            options={'ordering': ('name',), 'verbose_name': 'distrikt', 'verbose_name_plural': 'distrikter'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('paragraph',), 'verbose_name': 'paragraf', 'verbose_name_plural': 'paragraffer'},
        ),
        migrations.AlterModelOptions(
            name='serviceprovider',
            options={'ordering': ('name',), 'verbose_name': 'leverandør', 'verbose_name_plural': 'leverandører'},
        ),
        migrations.AlterModelOptions(
            name='targetgroup',
            options={'ordering': ('name',), 'verbose_name': 'målgruppe', 'verbose_name_plural': 'målgrupper'},
        ),
    ]
