# Generated by Django 2.2.9 on 2020-05-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_migrate_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_cost_type',
            field=models.CharField(choices=[('FIXED', 'fast beløb'), ('PER_UNIT', 'pris pr. enhed'), ('GLOBAL_RATE', 'takst')], default='FIXED', max_length=128, verbose_name='betalingstype'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Rate', verbose_name='takst'),
        ),
    ]
