# Generated by Django 2.2.9 on 2020-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_auto_20200526_1027"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityDetailsSupplementaryActivityProxy",
            fields=[],
            options={
                "verbose_name": "aktivitetsdetalje",
                "verbose_name_plural": "aktivitetsdetalje",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.activitydetails_supplementary_activity_for",),
        ),
        migrations.CreateModel(
            name="SectionEffortStepProxy",
            fields=[],
            options={
                "verbose_name": "paragraf",
                "verbose_name_plural": "paragraf",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.section_allowed_for_steps",),
        ),
        migrations.AlterField(
            model_name="activitydetails",
            name="main_activities",
            field=models.ManyToManyField(
                blank=True,
                help_text="Denne aktivitetsdetalje kan være følgeudgift for disse hovedydelser.<br>",
                related_name="supplementary_activities",
                to="core.ActivityDetails",
                verbose_name="hovedydelser",
            ),
        ),
        migrations.AlterField(
            model_name="effort",
            name="allowed_for_target_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="efforts",
                to="core.TargetGroup",
                verbose_name="målgrupper",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="allowed_for_steps",
            field=models.ManyToManyField(
                blank=True,
                related_name="sections",
                to="core.EffortStep",
                verbose_name="trin i indsatstrappen",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="allowed_for_target_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="sections",
                to="core.TargetGroup",
                verbose_name="målgrupper",
            ),
        ),
        migrations.AlterField(
            model_name="sectioninfo",
            name="supplementary_activity_main_account_number",
            field=models.CharField(
                blank=True,
                help_text="Et hovedkontonummer der skal bruges, hvis en følgeudgift har denne aktivitetsdetalje som hovedydelse.<br>",
                max_length=128,
                verbose_name="hovedkontonummer for følgeudgift",
            ),
        ),
    ]
