# Generated by Django 2.2.9 on 2020-05-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20200526_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='effort_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.EffortStep', verbose_name='indsatstrappe'),
        ),
        migrations.AlterField(
            model_name='case',
            name='scaling_step',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='skaleringstrappe'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='scaling_step',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='skaleringstrappe'),
        ),
    ]
