# Generated by Django 2.2.9 on 2020-05-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20200525_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentschedule',
            old_name='rate',
            new_name='payment_rate',
        ),
    ]
