# Generated by Django 2.2.9 on 2020-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_remove_duplicate_section_infos"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sectioninfo",
            constraint=models.UniqueConstraint(
                fields=("activity_details", "section"),
                name="unique_section_activity_details",
            ),
        ),
    ]
