# Generated by Django 2.2.9 on 2020-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_auto_20200528_1211"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalPaymentRecipient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, verbose_name="navn"),
                ),
            ],
            options={
                "verbose_name": "intern betalingsmodtager",
                "verbose_name_plural": "interne betalingsmodtagere",
            },
        ),
    ]
