# Generated by Django 2.2.13 on 2020-06-05 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20200528_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_cost_type',
            field=models.CharField(choices=[('FIXED', 'fast beløb'), ('PER_UNIT', 'pris pr. enhed'), ('GLOBAL_RATE', 'takst')], default='FIXED', max_length=128, verbose_name='betalingstype'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Rate', verbose_name='takst'),
        ),
    ]
