# Generated by Django 2.2.9 on 2020-06-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_create_internal_payment_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='recipient_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID'),
        ),
    ]
