# Generated by Django 2.2.13 on 2020-06-05 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20200605_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_day_of_month',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='betales d.'),
        ),
    ]
