# Generated by Django 2.2.13 on 2020-06-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20200605_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': 'takst', 'verbose_name_plural': 'takster'},
        ),
        migrations.AlterModelOptions(
            name='rateperdate',
            options={'ordering': ('-start_date',), 'verbose_name': 'takst for datoer', 'verbose_name_plural': 'takster for datoer'},
        ),
    ]
