# Generated by Django 2.2.9 on 2020-06-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20200602_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='created_new',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='modified_new',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='user_created_new',
            new_name='user_created',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='user_modified_new',
            new_name='user_modified',
        ),
        migrations.RenameField(
            model_name='appropriation',
            old_name='created_new',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='appropriation',
            old_name='modified_new',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='appropriation',
            old_name='user_created_new',
            new_name='user_created',
        ),
        migrations.RenameField(
            model_name='appropriation',
            old_name='user_modified_new',
            new_name='user_modified',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='created_new',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='modified_new',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='user_created_new',
            new_name='user_created',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='user_modified_new',
            new_name='user_modified',
        ),
        migrations.RenameField(
            model_name='historicalcase',
            old_name='created_new',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='historicalcase',
            old_name='modified_new',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='historicalcase',
            old_name='user_created_new',
            new_name='user_created',
        ),
        migrations.RenameField(
            model_name='historicalcase',
            old_name='user_modified_new',
            new_name='user_modified',
        ),
        migrations.RenameField(
            model_name='relatedperson',
            old_name='created_new',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='relatedperson',
            old_name='modified_new',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='relatedperson',
            old_name='user_created_new',
            new_name='user_created',
        ),
        migrations.RenameField(
            model_name='relatedperson',
            old_name='user_modified_new',
            new_name='user_modified',
        ),
    ]
