# Generated by Django 2.2.13 on 2020-06-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20200602_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_cost_type',
            field=models.CharField(choices=[('FIXED', 'fast beløb'), ('PER_UNIT', 'pris pr. enhed'), ('GLOBAL_RATE', 'takst')], default='FIXED', max_length=128, verbose_name='betalingstype'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Rate', verbose_name='takst'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='beløb'),
        ),
    ]
