# Generated by Django 2.2.13 on 2020-06-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20200610_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='payment_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_per_unit', to='core.PaymentSchedule', verbose_name='betalingsplan'),
        ),
    ]
