# Generated by Django 2.2.13 on 2020-06-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_migrate_old_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktiv'),
        ),
    ]
