# Generated by Django 2.2.13 on 2020-06-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_rate_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='needs_update',
            field=models.BooleanField(default=False, verbose_name='skal genberegnes'),
        ),
    ]
