# Generated by Django 2.2.13 on 2020-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20200618_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='needs_recalculation',
            field=models.BooleanField(default=False, verbose_name='skal genberegnes'),
        ),
    ]
