# Generated by Django 2.2.13 on 2020-06-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_rate_needs_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDateExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='dato')),
            ],
            options={
                'verbose_name': 'betalingsdato undtagelse',
                'verbose_name_plural': 'betalingsdato undtagelser',
                'ordering': ('-date',),
            },
        ),
    ]
