# Generated by Django 2.2.13 on 2020-06-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_historicalpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=128, verbose_name='kontoalias')),
                ('activity_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ActivityDetails', verbose_name='aktivitetsdetalje', related_name='account_aliases')),
                ('section_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SectionInfo', verbose_name='paragraf-info', related_name='account_aliases')),
            ],
            options={
                'verbose_name': 'kontoalias',
                'verbose_name_plural': 'kontoalias',
            },
        ),
        migrations.AddConstraint(
            model_name='accountalias',
            constraint=models.UniqueConstraint(fields=('activity_details', 'section_info'), name='unique_section_info_activity_details'),
        ),
        migrations.AddField(
            model_name='payment',
            name='saved_account_alias',
            field=models.CharField(blank=True, max_length=128, verbose_name='gemt kontoalias'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='saved_account_alias',
            field=models.CharField(blank=True, max_length=128, verbose_name='gemt kontoalias'),
        ),
    ]
