# Generated by Django 2.2.13 on 2020-07-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_import_account_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='betalingsdato'),
        ),
    ]
