# Generated by Django 2.2.13 on 2020-07-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_migrate_payment_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='startdato'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_date',
            field=models.DateField(blank=True, help_text='dette felt er obligatorisk for og angår kun engangsbetalinger', null=True, verbose_name='betalingsdato'),
        ),
    ]
