# Generated by Django 2.2.16 on 2020-09-09 12:10

from django.db import migrations, models

def migrate_existing_payment_schedules(apps, schema_editor):
    PaymentSchedule = apps.get_model("core", "PaymentSchedule")

    for payment_schedule in PaymentSchedule.objects.all():
        # The old "per unit" payment types are now all a kind of
        # "RUNNING_PAYMENT".
        if payment_schedule.payment_type in ["PER_HOUR_PAYMENT", "PER_DAY_PAYMENT", "PER_KM_PAYMENT"]:
            payment_schedule.payment_type = "RUNNING_PAYMENT"
            payment_schedule.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20200903_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_type',
            field=models.CharField(choices=[('ONE_TIME_PAYMENT', 'Engangsudgift'), ('RUNNING_PAYMENT', 'Fast beløb, løbende'), ('INDIVIDUAL_PAYMENT', 'Individuel')], max_length=128, verbose_name='betalingstype'),
        ),
        migrations.RunPython(migrate_existing_payment_schedules),
    ]
