# Generated by Django 2.2.16 on 2020-09-08 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20200903_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrateperdate',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ændret af'),
        ),
        migrations.AddField(
            model_name='historicalrateperdate',
            name='changed_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='rateperdate',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_and_price_changes', to=settings.AUTH_USER_MODEL, verbose_name='Ændret af'),
        ),
        migrations.AddField(
            model_name='rateperdate',
            name='changed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
