# Generated by Django 2.2.16 on 2020-09-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20200909_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_cost_type',
            field=models.CharField(choices=[('FIXED', 'fast beløb'), ('PER_UNIT', 'pris pr. enhed'), ('GLOBAL_RATE', 'takst')], default='FIXED', max_length=128, null=True, verbose_name='betalingspristype'),
        ),
    ]
