# Generated by Django 2.2.16 on 2020-12-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20201116_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='team',
        ),
        migrations.RemoveField(
            model_name='historicalcase',
            name='team',
        ),
    ]
