# Generated by Django 2.2.16 on 2021-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20201201_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAliasMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_account_number', models.CharField(blank=True, help_text="dimensionen 'Hovedkonto' i kontostrengen", max_length=128, verbose_name='hovedkontonummer')),
                ('activity_number', models.CharField(blank=True, help_text="dimensionen 'Aktivitet' i kontostrengen", max_length=128, verbose_name='aktivitetsnummer')),
                ('alias', models.CharField(blank=True, max_length=128, verbose_name='kontoalias')),
            ],
            options={
                'verbose_name': 'nyt kontoalias',
                'verbose_name_plural': 'nye kontoalias',
            },
        ),
        migrations.AddConstraint(
            model_name='accountaliasmapping',
            constraint=models.UniqueConstraint(fields=('main_account_number', 'activity_number'), name='unique_main_account_number_activity_number'),
        ),
    ]
