# Generated by Django 2.2.16 on 2021-01-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20210205_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('category_id', models.CharField(max_length=6, verbose_name='kategori ID')),
                ('name', models.CharField(max_length=128, verbose_name='navn')),
            ],
            options={'verbose_name': 'aktivitetskategori', 'verbose_name_plural': 'aktivitetskategorier'},
        ),
        migrations.AddField(
            model_name='sectioninfo',
            name='activity_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_infos', to='core.ActivityCategory', verbose_name='aktivitetskategori'),
        ),
    ]
