# Generated by Django 2.2.16 on 2021-02-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20210128_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioninfo',
            name='activity_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_infos', to='core.ActivityCategory', verbose_name='aktivitetskategori'),
        ),
    ]
