# Generated by Django 2.2.16 on 2021-06-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20210222_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountaliasmapping',
            options={'verbose_name': 'kontoalias', 'verbose_name_plural': 'kontoalias'},
        ),
        migrations.DeleteModel(
            name='AccountAlias',
        ),
    ]
