# Generated by Django 2.2.16 on 2021-07-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_delete_existing_service_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='business_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='branchekode'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='business_code_text',
            field=models.CharField(blank=True, max_length=128, verbose_name='branchetekst'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='status',
            field=models.CharField(blank=True, max_length=128, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='street',
            field=models.CharField(blank=True, max_length=128, verbose_name='vejnavn'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='street_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='vejnummer'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='post_district',
            field=models.CharField(blank=True, max_length=128, verbose_name='postdistrikt'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='zip_code',
            field=models.CharField(blank=True, max_length=128, verbose_name='postnummer'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='cvr_number',
            field=models.CharField(blank=True, max_length=8, unique=True, verbose_name='cvr-nummer'),
        ),
    ]
