# Generated by Django 2.2.16 on 2021-07-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0096_auto_20210729_1433")]

    operations = [
        migrations.AddField(
            model_name="internalpaymentrecipient",
            name="active",
            field=models.BooleanField(default=True, verbose_name="aktiv"),
        ),
        migrations.AddField(
            model_name="team",
            name="active",
            field=models.BooleanField(default=True, verbose_name="aktiv"),
        ),
        migrations.AddField(
            model_name="paymentmethoddetails",
            name="active",
            field=models.BooleanField(default=True, verbose_name="aktiv"),
        ),
        migrations.AddField(
            model_name="sectioninfo",
            name="active",
            field=models.BooleanField(default=True, verbose_name="aktiv"),
        ),
    ]
