# Generated by Django 2.2.16 on 2021-10-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20210728_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='modifies',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to='core.Activity', verbose_name='justeres af aktivitet'),
        ),
    ]
