# Generated by Django 2.2.16 on 2021-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20210728_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioninfo',
            name='dst_code',
            field=models.CharField(blank=True, help_text='Værdikode til brug ved levering af data til Danmarks Statistik.', max_length=128, verbose_name='DST værdikode'),
        ),
    ]
