# Generated by Django 2.2.16 on 2021-10-28 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_section_dst_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcase',
            name='acting_municipality',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.Municipality', verbose_name='handlekommune'),
        ),
    ]
