# Generated by Django 2.2.25 on 2022-01-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_historicalcase_acting_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='default_for_dst_handicap',
            field=models.BooleanField(blank=True, default=True, help_text="Hvorvidt denne paragraf skal bruges som standard til DST udtræk for 'Handicap'.", verbose_name="standard for DST 'Handicap'"),
        ),
        migrations.AddField(
            model_name='section',
            name='default_for_dst_preventative_measures',
            field=models.BooleanField(blank=True, default=True, help_text="Hvorvidt denne paragraf skal bruges som standard til DST udtræk for 'Forebyggende Foranstaltninger'.", verbose_name="standard for DST 'Forebyggende Foranstaltninger'"),
        ),
    ]
