# Generated by Django 2.2.16 on 2022-01-07 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20220104_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSTPayload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='navn')),
                ('content', models.TextField(verbose_name='indhold')),
                ('from_date', models.DateField(null=True, verbose_name='fra dato (skæringsdato)')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='genereringsdato')),
                ('dst_type', models.CharField(choices=[('PREVENTATIVE_MEASURES', 'forebyggende foranstaltninger'), ('HANDICAP', 'handicap')], max_length=128, verbose_name='type')),
            ],
            options={
                'verbose_name': 'DST udtræk',
                'verbose_name_plural': 'DST udtræk',
                'ordering': ('-date',),
            },
        ),
    ]
