# Generated by Django 2.2.16 on 2022-01-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_dstpayload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='default_for_dst_handicap',
            new_name='dst_handicap',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='default_for_dst_preventative_measures',
            new_name='dst_preventative_measures',

        ),
        migrations.AlterField(
            model_name='section',
            name='dst_handicap',
            field=models.BooleanField(blank=True, default=True, help_text="Hvorvidt denne paragraf skal bruges til DST udtræk for 'Handicap'.", verbose_name="DST 'Handicap'"),
        ),
        migrations.AlterField(
            model_name='section',
            name='dst_preventative_measures',
            field=models.BooleanField(blank=True, default=True, help_text="Hvorvidt denne paragraf skal bruges til DST udtræk for 'Forebyggende Foranstaltninger'.", verbose_name="DST 'Forebyggende Foranstaltninger'"),
        ),
    ]
