# Generated by Django 2.2.26 on 2022-01-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20220118_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='dstpayload',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='til dato (skæringsdato)'),
        ),
        migrations.AlterField(
            model_name='dstpayload',
            name='from_date',
            field=models.DateField(blank=True, null=True, verbose_name='fra dato (skæringsdato)'),
        ),
    ]
